spring:
  application:
    name: intern_application

  # H2 Database Config (In-Memory)
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
    driver-class-name: org.h2.Driver

  # Enable H2 Console (Access at http://localhost:8080/h2-console)
  h2:
    console:
      enabled: true

  # JPA / Hibernate Settings
  jpa:
    show-sql: true             # Print SQL in console
    hibernate:
      ddl-auto: update         # Create/Update tables automatically
    properties:
      hibernate:
        format_sql: true       # Make SQL pretty in console